<div id="openpos-rma">
    <p>This order is a refund, as the customer has returned more than they are purchasing.</p>
    <p>Select refund method below, then refund the amount to the customer.</p>
    <br>
    <br>

    <div class="grid grid-cols-1 md:grid-cols-2 gap-4">
        <?php foreach($magewire->paymentMethods as $code => $paymentMethod): ?>
            <div class="w-full mb-4">
                <input type="radio" id="<?=$code?>" name="refund_method" wire:click="$emit('save', '<?=$code?>')">
                <label for="<?=$code?>"><?= $paymentMethod['title'] ?></label><br>
            </div>
        <?php endforeach; ?>
    </div>
</div>
